version: '3.8'

services:
  openvpn:
    build:
      context: .
      dockerfile: Dockerfile.openvpn
    image: openvpn:test
    command: /etc/openvpn/setup/bootstrap.sh
    networks:
      - openvpn-ui-network
    environment:
      OPENVPN_SERVER_NET: "192.168.100.0"
      OPENVPN_SERVER_MASK: "255.255.255.0"
      OPENVPN_PASSWORD_AUTH: "true"
    cap_add:
      - NET_ADMIN
    ports:
      - "8000:1194"
    volumes:
      - ./easyrsa:/etc/openvpn/easyrsa
      - ./ccd:/etc/openvpn/ccd
  openvpn-ui-api:
    build:
      context: ./openvpn-ui-fast-api
    image: openvpn-ui-api:test
    ports:
      - "8080:8080"
    command: python3 /app/main.py
    networks:
      - openvpn-ui-network
    environment:
      OPENVPN_EASYRSA_PATH: "/opt/easyrsa"
      OPENVPN_INDEX_TXT_PATH: "/opt/easyrsa/pki/index.txt"
      OPENVPN_CCD_PATH: "/opt/ccd"
      OPENVPN_LISTEN_HOST: "127.0.0.1"
      OPENVPN_LISTEN_PORT: 8000
      OPENVPN_PASSWORD_AUTH: "true"
      OPENVPN_CCD_CONFIG_PATH: "/etc/openvpn/ccd"
    volumes:
      - ./easyrsa:/opt/easyrsa
      - ./ccd:/opt/ccd
      - ./db:/opt/db
  openvpn-ui:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_HOST: http://localhost
        NEXT_PUBLIC_API_PORT: 8080
        NEXT_PUBLIC_AUTH_PASS: true
    image: openvpn-ui:v0.1.0
    ports:
      - "3000:3000"
    networks:
      - openvpn-ui-network
    # As we are building the static client side app we cannot pass the environment variables
#    environment:
#      NEXT_PUBLIC_AUTH_PASS: "true"
#      NEXT_PUBLIC_API_PORT: 8000
#      NEXT_PUBLIC_API_HOST: "http://openvpn-ui-api"


networks:
  openvpn-ui-network:
    driver: bridge